// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpAobmHFdqVwdsXYU8lrinx1hqhabhYu4',
    appId: '1:897519716564:web:78cb9943d079ba9fde9341',
    messagingSenderId: '897519716564',
    projectId: 'medicare-2f425',
    authDomain: 'medicare-2f425.firebaseapp.com',
    storageBucket: 'medicare-2f425.appspot.com',
    measurementId: 'G-2NSCNTY9PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXEJQHk2xBzN5gJMkGqaN8UPJeXYOgEMc',
    appId: '1:897519716564:android:86bfb697a2d58c72de9341',
    messagingSenderId: '897519716564',
    projectId: 'medicare-2f425',
    storageBucket: 'medicare-2f425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGeBCt-wTQyQx6mUORhT76kOVmDbfWYzg',
    appId: '1:897519716564:ios:ca3c73a6daa92729de9341',
    messagingSenderId: '897519716564',
    projectId: 'medicare-2f425',
    storageBucket: 'medicare-2f425.appspot.com',
    iosBundleId: 'com.example.mediCare',
  );


}
